version: "2"

services:
  es:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana
    ports:
      - "5601:5601"
    links:
      - "es:elasticsearch"


